### ISSUE TITLE
Python 3 test

### ISSUE THREAD

**Issue by amjadraza** [LocalBitcoins/lbcapi#1]
anybody tested this api on python 3.5?

I am having issues connecting using python 3.

**Comment by Maaxion** [comment]
I'm afraid this library has not been tested with Python 3, only with Python 2.7. Can you give any details on the issues you've been having?

**Comment by amjadraza** [comment]
Its working with python, was just wondering if its compatible with python
3.

Thanks

**Comment by ghost** [comment]
It's definitely not working in Python 3.

**Comment by zxcV32** [comment]
working on python 3.7

**Comment by unchainedio** [comment]
i am also having issues running this lib with python 3...  Is there a planned fix for this?  python2.7 will most likely be deprecated soon..

**Comment by Chuox** [comment]
I'm using this one for Python 3 [https://github.com/6ones/lbcapi3](https://github.com/6ones/lbcapi3)
Everything ok so far

**Comment by azizij4** [comment]
#19  first install local btc api

-  pip install lbcapi

 after installing 

from lbcapi3 import api 

not this import lbcapi 

for me its works in python3  , thank
