### ISSUE TITLE
Installing lbcapi

### ISSUE THREAD

**Issue by wafflemakr** [LocalBitcoins/lbcapi#11]
When running:

`pip install lbcapi`

I get:

`Could not find a version that satisfies the requirement lbcapi (from versions: )
No matching distribution found for lbcapi`

Any help? Thanks

**Comment by henu** [comment]
Trying with Python 3?

**Comment by hasn1** [comment]
im newbie on here and i got same error on CMD
"ERROR: Could not find a version that satisfies the requirement lbcapi (from versions: none)
ERROR: No matching distribution found for lbcapi"

**Comment by Chuox** [comment]
I'm using this one for Python 3 https://github.com/6ones/lbcapi3
Everything ok so far
