### ISSUE TITLE
Usage example of POST endpoint

### ISSUE THREAD

**Issue by leosjoberg** [LocalBitcoins/lbcapi#12]
Not quite getting POST method endpoints with several parameters to work.

For example, the /api/feedback/{username}/ endpoint allows for 2 arguments, both strings. What would this look like? https://localbitcoins.com/api-docs/#feedback

conn.call('POST', '/api/contact_release/' + contact_id + '/').json() 

Where/how are the arguments inserted? A usage example of a POST endpoint like the GET example in the README would be immensely helpful.

**Comment by leosjoberg** [comment]
Managed to figure it out. The params parameter accepts a JSON. 

conn.call('POST', '/api/contact_release/' + contact_id + '/', params={"feedback": "positive", "msg": "Fast trade!"}).json()

**Comment by rubru70** [comment]
> Managed to figure it out. The params parameter accepts a JSON.
> 
> conn.call('POST', '/api/contact_release/' + contact_id + '/', params={"feedback": "positive", "msg": "Fast trade!"}).json()

Thanks!
